#!/usr/bin/env bash
set -eo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/../../../.." && pwd)"
ENV_DIR="${ENV_DIR:-${ROOT_DIR}/.venv/drkernel310}"

export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-4,5,6,7}"
export PATH="${ENV_DIR}/bin:${PATH}"
export PYTHONPATH="${ROOT_DIR}/drkernel:${ROOT_DIR}:${ROOT_DIR}/drkernel/verl:${PYTHONPATH:-}"
export WANDB_MODE="${WANDB_MODE:-offline}"
export TOKENIZERS_PARALLELISM="${TOKENIZERS_PARALLELISM:-false}"
export MERLIN_JOB_ID="${MERLIN_JOB_ID:-local-drkernel}"
export ARNOLD_MONITOR_TRIAL_ID="${ARNOLD_MONITOR_TRIAL_ID:-local}"
export GIT_COMMIT_URL="${GIT_COMMIT_URL:-local}"

export ARNOLD_WORKER_NUM="${ARNOLD_WORKER_NUM:-1}"
export ARNOLD_WORKER_GPU="${ARNOLD_WORKER_GPU:-4}"
export N_GPUS_PER_NODE="${N_GPUS_PER_NODE:-4}"
export KERNELGYM_SERVER_URL="${KERNELGYM_SERVER_URL:-http://127.0.0.1:10907}"
export HDFS_DATA_PATH="${HDFS_DATA_PATH:-${ROOT_DIR}/drkernel/data}"
export HDFS_CHECKPOINT_PATH="${HDFS_CHECKPOINT_PATH:-${ROOT_DIR}/checkpoints/drkernel}"

cd "${ROOT_DIR}/drkernel"

TRAIN_DATASET=("hkust-nlp/drkernel-rl-data")
VALID_DATASET=("hkust-nlp/drkernel-validation-data")
MODEL_NAME="${MODEL_NAME:-drkernel-8b-coldstart}"
MODEL_PATH="${MODEL_PATH:-${ROOT_DIR}/models/hkust-nlp/drkernel-8b-coldstart}"

RUN_NAME="${RUN_NAME:-drkernel-8b-coldstart-local}"
REWARD_MANAGER=kernel_async
REWARD_FUNC_NAME="calculate_reward_speedup"

ALGORITHM="trloo"

SPEEDUP_REWARD_UPPER_BOUND=3.0
SPEEDUP_REWARD_LOWER_BOUND=0.0

ROLLOUT_RS="geometric"
ROLLOUT_TOKEN_VETO_THRESHOLD=1e-4
ROLLOUT_RS_KWARGS="{lower:0.999,upper:1.001}"

COVERAGE_RS="turn"
COVERAGE_RS_THRESHOLD=0.3
COVERAGE_RS_FACTOR=0.1
COVERAGE_RS_KEY="time_coverage"

COVERAGE_REWARD_TYPE="time_coverage"
COVERAGE_REWARD_WEIGHT=0.5
COVERAGE_REWARD_ENABLE=True

REWARD_TASK_TIMEOUT=300
REWARD_TIMEOUT=1800
REWARD_ACQUIRE_TIMEOUT=2400
REWARD_MAX_CONCURRENT=32
REWARD_MAX_RETRIES=3
REWARD_PRINT_STATUS=True
NUM_PERF_TRIALS=100
REWARD_TASK_TIMEOUT_CLIENT=2400

VAL_BEFORE_TRAIN=True
IS_GET_LAST_TURN=True

ENABLE_MULTI_TURN=True
MAX_TURN=3
N_VAL=8
ACTOR_OPTIMIZER_OFFLOAD=True
ACTOR_PARAMETER_OFFLOAD=True
LEARNING_RATE=1e-6

TRAIN_BATCH_SIZE=16
PPO_MINI_BATCH_SIZE=16

AUTOMATIC_OVERSAMPLING=False
REJECTION_SAMPLE=True

PPO_MICRO_TOKEN=null
CLIP_RATIO=0.2_0.28
ENTROPY_CLIP_RATE=0.0
GRAD_CLIP=1.0
VLLM_IS_THRESHOLD=2.0
EXTREME_RISK_PROB_THRESHOLD=null
KL_LOSS_COEF=0.0
ENTROPY_COEFFIENT=0.0
KL_LOSS_TYPE="low_var_kl"
TEMPERATURE=1.0
MIN_P=0.0
TOP_P=1.0
TOP_K=-1
ROLLOUT_N=16
KL_COEF=0.0
TOTAL_EPOCHS=1000
ROLLOUT_GPU_MEMORY_UTIL=0.75

SAVE_FREQ=10
TEST_FREQ=10
ROLLOUT_TENSOR_MODEL_PARALLEL_SIZE=1
SP_SIZE=4
APPLY_CHAT_TEMPLATE=True
FREE_CACHE_ENGINE=True
ENFORCE_EAGER=False
NNODES="${ARNOLD_WORKER_NUM}"
GPUS_PER_NODE="${ARNOLD_WORKER_GPU}"

MAX_PROMPT_LENGTH=10240
MAX_RESPONSE_LENGTH=8192
PROMPT_OVERSAMPLING_FACTOR=1.0
SAMPLE_OVERSAMPLING_FACTOR=1.0
SAMPLE_SELECTION_STRATEGY=efficiency_stochastic
MAX_SKIP_STEPS=5

source "${SCRIPT_DIR}/train_rl_common.sh"
main "$@"
